import React from "react";
import { useState, useEffect } from "react";
import Head from "next/head";
import getPosts from "../components/getPosts";

export default function Home() {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    getPosts().then(posts => setPosts(posts));
  }, []); 

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container mx-auto w-full sm:w-10/12 md:w-8/12 lg:w-6/12 xl:w-6/12 p-4">
          <h1 className="font-bold text-2xl">Welcome to my blog</h1>
          {
            // the blog posts will be rendered here
            posts.map((post) => {
              return (
                <div className="flex flex-col p-5 rounded-lg border-2 border-gray-200 mt-10" key={post.id}>
                  <h2 className="text-xl font-bold">{post.title}</h2>
                  <p>{post.content}</p>
                  <span className="text-sm">{post.date}</span>
                </div>
              );
            })
          }
        </div>
      </main>
    </div>
  );
}
