import React from "react";
import { useState, useEffect } from "react";
import Head from "next/head";
import getPosts from "../components/getPosts";
import { marked } from "marked";

export default function Home() {
  const [posts, setPosts] = useState([]);

  const getPosts_ = async () => {
    const posts = await getPosts();
    setPosts(posts);
  }

  useEffect(() => {
    getPosts_();
  }, []); 

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container mx-auto w-full sm:w-10/12 md:w-8/12 lg:w-6/12 xl:w-6/12 p-4">
          <h1 className="font-bold text-2xl">Welcome to my blog</h1>
          {
            // the blog posts will be rendered here
            posts.map((post) => {
              return (
                <div className="flex flex-col p-5 rounded-lg border-2 border-gray-200 mt-10" key={post.id}>
                  <h2 className="text-xl font-bold">{post.title}</h2>
                  <div dangerouslySetInnerHTML={
                    {__html: marked(post.content)}
                    }></div>
                  <span className="text-sm mb-6">{post.date}</span>
                  <a href={`/${post.id}`} className=" text-center w-36 py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-50 focus:outline-none bg-gray-600 rounded-lg border border-gray-200 hover:bg-gray-100 hover:ring-gray-800 hover:ring-1 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-20">Read More</a>

                </div>
              );
            })
          }
        </div>
      </main>
    </div>
  );
}
